### PR TITLE
Implement batch updates

### PR DESCRIPTION
**Pull request by davidmoten**
Got this going now. Test coverage is reasonable making use of Mockito. 

When `con.executeUpdate` gets called in `QueryUpdateOnSubscribe` and batching is active then a particular wrapper for the connection is used that returns a cached `PreparedStatement` that translates the call to `con.addBatch` and when the number of batches added equals `batchSize` `con.executeBatch` is also called.

Things got a bit tricky when I realized that on commit we need to execute any outstanding batches yet still return the update counts to downstream. The commit operation was not designed to emit counts so the logic was moved to the last update pass through `QueryUpdateOnSubscribe` (detected by a new operator in *rxjava-extras* `Transformers.mapLast`). As a consequence the parameter groups are read one in advance so that we always know when we are at the last group.

### CODE REVIEW

**Comment by thomasnield** [comment]
NICE!  Yeah I found handling the outstanding batched was the hardest part,  but I didn't do it anywhere near as robustly as you did. Thank you for all your amazing work as usual, and I'll distribute a build to my coworkers for testing tomorrow. I am really excited to play with this. 

How much testing did you want help with before a release?

**Comment by davidmoten** [comment]
Beaut, thanks Thomas. I thought I'd build an RC release in a couple of
hours (out swanning around with a couple of weeks off at the moment). Test
as you can thanks.

**Comment by davidmoten** [comment]
7.3-RC1 available on Maven Central now

**Comment by thomasnield** [comment]
Will do,  thanks again a lot! By the way, is it up to the user to handle autoCommit or does this API turn it on and off now too as needed?

**Comment by EmteZogaf** [comment]
I'll try it out soon, too.

**Pull request merged**
