### PR TITLE
Allow setting of Fetch_Size on select queries

### PR DESCRIPTION
**Pull request by michele-mancioppi**
Expose the [fetch_size](https://docs.oracle.com/javase/8/docs/api/java/sql/Statement.html#setFetchSize-int-) setting for select queries.

### CODE REVIEW

**Comment by michele-mancioppi** [comment]
Hi, any chance for this to get merged? :-)

**Comment by davidmoten** [comment]
Thanks @michele-mancioppi! Very useful contribution. I'll knock up a release now and fix a couple of typos in the README.

**Comment by michele-mancioppi** [comment]
Thanks! I also have seen now the PR's typos in the README and cringed really, really hard ;-)

**Comment by davidmoten** [comment]
0.7.6 is on Maven Central with your PR.

**Pull request merged**
