### PR TITLE
Out of the box support for javax.sql.DataSource

### PR DESCRIPTION
**Pull request by sparty02**
Nothing fancy, just putting in some native helpers to handle javax.sql.DataSource based connection pools.

### CODE REVIEW

**Comment by davidmoten** [comment]
Thanks for the contribution! Can you remove unused dependency assertj and use spaces instead of tabs (the diff in git and github always shows tabs as eight spaces so it's obvious)?

**Comment by davidmoten** [comment]
Would you like me to make the necessary changes or would you like to update the PR?

**Comment by sparty02** [comment]
Sorry for the delay, the week just started out crazy for me.  I can make these updates!

**Comment by sparty02** [comment]
@davidmoten I think I addressed all of the tab --> space issues and remove the unused dep for now.  I think this is ready to go!  Let me know if you have any other feedback.

**Comment by davidmoten** [comment]
Thanks!

**Comment by davidmoten** [comment]
0.5.10 released with this change.

**Pull request merged**
