### PR TITLE
[WIP] Execute Update Query as Batch Update

### PR DESCRIPTION
**Pull request by EmteZogaf**
A simple approach to execute batch updates. I needed this for a work project executing ~800M insert queries per run. Hope this functionality will be added this way or another as I really like avoiding java.sql.*.

I marked it as "work in progress" because it lacks test cases and documentation and probably needs some code refactoring.

### CODE REVIEW

**Comment by davidmoten** [comment]
Looks like a good idea Emte, thanks. I'll review in more detail later. I've been actively making changes to master in the last week or so which makes it hard for you to knock up mergeable PRs but could you rebase to master?

**Comment by EmteZogaf** [comment]
Rebased to master and provided simple tests. I had to enable backpressure buffer to support batch sizes of 1000 or more.

**Comment by davidmoten** [comment]
Waiting for a buffer of parameter groups is contrary to the normal reactive approach which is to push results downstream as far as we can as soon as we can (i.e. call `ps.addBatch()` with a parameter group as soon as we have it. 

We can simplify `QueryUpdateOnSubscribe` by reverting to being passed `List<Parameter>` instead of `List<List<Parameter>>` and buffer size and keeping a count local to the subscriber so we know when to execute a batch. For backpressure conformance when a parameter group is processed with `ps.addBatch` we also request 1 from upstream because the stream could stall and then we could use `QueuedProducer` to handle emitting the results of `ps.executeBatch`.

`onBackpressureBuffer` can be a problem in backpressure situations because it always requests `Long.MAX_VALUE` from upstream and to get proper backpressure support we would prefer it only requested what was requested of it. I'll raise this issue on RxJava soonish (perhaps when I have a suggestion in mind).

**Comment by EmteZogaf** [comment]
I don't like the `List<List<Parameter>>` either. But I don't see which subscriber should keep the counter. Right now `QueryUpdateOnSubscribe` is created for each parameter group, gets a connection, creates the `PreparedStatement`, executes the query with the given parameter group and pushes a new Observable with the update count which is flattened with the other results if there are more than one parameter group.

In order to add `batchSize` parameter groups both the `PreparedStatement` and the connection need to stay open till the batch can be executed. This can be problematic if it's the only available connection. So I think it's better to buffer the parameter groups and only occupy a connection for the shortest time possible. But maybe I miss something.

**Comment by davidmoten** [comment]
yep you are right but we can control what the connection is and what happens when `prepareStatement` gets called. See these lines 

```java
state.con = query.context().connectionProvider().get();
state.ps = state.con.prepareStatement(jdbcQuery.sql());
```

If batching is enabled then the query context could return the same connection every time and the `prepareStatement` could return the same cached `PreparedStatement` every time till we are finished with that subscription. I haven't thought it all through yet but might work ok and prevent double buffering (first in a list, then in `addBatch`).

**Comment by EmteZogaf** [comment]
You are right, the current solution buffers the parameters twice.

So you would put the `QueryContext` into control over holding the state? Currently this workflow comes to my mind:
* if batch size > 1
  * cache the `Connection` and `PreparedStatement` the first time it's requested (keeping it open)
  * set an internal batch size counter to `batchSize`
  * for each `onNext` creating a `QueryUpdateOnSubscribe` hand over the cached connection and cached prepared statement and decrement the counter 
  * add the next parameter group to the batch
  * if the counter reached 0 execute the batch and reset counter
  * `onComplete` check if counter < `batchSize` and execute possible remaining batch
  * close prepared statement and connection
* if batch size = 1 fall back to current behaviour

**Comment by davidmoten** [comment]
Sorry for the delay in responding to this. 
The transaction logic already caches Connections by putting in a ThreadLocal variable. No async activity should be taking place within a transaction. We could do the same with the PreparedStatement but be careful to clear from ThreadLocal when finished. The connection would not be closed after each batch, no, otherwise batching is not really happening. I suppose you could be referring to pretending to close the connection, that's possible yes.

Don't worry about deadlock. If only one connection is available it is on the user to ensure proper use of their single resource (yes it could cause a stall). Perhaps some more explanation of this scenario should be put in the project README.

If  you'd like to proceed with working on this that would be great. If not I'll take it on because this enhancement is useful to me too at the moment.

**Comment by EmteZogaf** [comment]
I'm sorry too for responding so late. I'd like to finish this feature but I won't have time to do so in the next 2 weeks and it will definitely take longer for me digging into the code to implement it right. So if it's an urgent feature to you just go on.

**Comment by EmteZogaf** [comment]
Rebased. Trying to implement it the way you said...

**Comment by thomasnield** [comment]
Hey guys, what is the status of using batching in this library? We would like to take advantage of this kind of setup but in a reactive context. The performance gains would be helpful
http://examples.javacodegeeks.com/core-java/sql/jdbc-batch-insert-example/

**Comment by davidmoten** [comment]
Hi @thomasnield yep this is definitely good to have, just not a trivial job so haven't got round to it yet. I'll give it a shot soon if @EmteZogaf is quiet on that front.

**Comment by thomasnield** [comment]
Okay thank you, I will put aside some time to see if I can contribute more as well. Need to trawl the source code a few times though.

**Comment by davidmoten** [comment]
Work in progress is on the [batch-updates](https://github.com/davidmoten/rxjava-jdbc/tree/batch-updates) branch if you want to get involved.

**Comment by thomasnield** [comment]
Okay I'll play with it this weekend. Definitely would like to help any way I can.

**Comment by EmteZogaf** [comment]
Hi, I'm sorry, I totally forgot about this pull request. I tried to implement it but I'm not happy with the code. @davidmoten If you already started on this feature it's probably the best you finish it. I'm currently busy with other stuff.

**Comment by davidmoten** [comment]
@EmteZogaf no probs. It's quite a tricky one. My current attempt will be wound right back I'm sure. I need to rethink it.

**Comment by thomasnield** [comment]
The need for this has come up in my workplacemultiple times this week. When I get a moment I may try to contribute to this, although I fear I'm not deep in the weeds like you guys already are. It may take me some time.

**Comment by EmteZogaf** [comment]
I tried to finish the [batch-update](https://github.com/davidmoten/rxjava-jdbc/tree/batch-updates) which I made the pull request #49 for. It hasn't been rebased for a while. I'm using this state in my current project and haven't any errors yet, but it surely needs more thorough testing.

**Comment by thomasnield** [comment]
That sounds promising. So minus the testing and rebasing is it a finished product we can bring out of prototype? Is there anything I can do to help?

**Comment by EmteZogaf** [comment]
Testing it in your environment and your use cases would help to verify if it's actually working or not. And I would like to have some numbers to compare it against the current version.

I have about 300 runs inserting 35k rows straight which all went fine. I additionally did 10 runs inserting ~27M rows which also went fine. I'm using postgres (testing) and oracle (production).

I didn't do any comparison to the current release version as I am pretty busy since 4 months to finish my project which is scheduled to be final in 2 weeks. After that I'd like to do more testing and help getting this into master soon. But I think it first needs a code review of @davidmoten or someone else.

**Comment by thomasnield** [comment]
I'll take a look this coming week. I'm glad this effort is still going on. I'll help any way I can.

**Comment by davidmoten** [comment]
Thanks for the prompts on this I might be able to look at this later this week. That's great you've made some progress @EmteZogaf will you be able to update this PR so that we can review?

**Comment by thomasnield** [comment]
@EmteZogaf  I'm inspecting your fork right now and going to play with it.

**Comment by thomasnield** [comment]
Something is a little odd I'm testing against a SQLite database with a simple table.

```sql
CREATE TABLE TEST_TABLE (
    ID    INTEGER PRIMARY KEY,
    VALUE INTEGER
);
``` 

I'm running this Kotlin code to test the INSERT of values. 

```kotlin
val conn = ConnectionProviderFromUrl("jdbc:sqlite:C:/git/rxjava-jdbc-batch-test/test.db").get().apply {
    autoCommit = false
}
val db =Database.from(conn)
data class Item(val id: Int, val value: Int)

fun main(args: Array<String>) {

    println(LocalDateTime.now())

    db.update("INSERT INTO TEST_TABLE (VALUE) VALUES(?)")
        .parameters(Observable.range(1,10000))
        .batchSize(1000)
        .returnGeneratedKeys()
        .getAs(Int::class.java)
        .subscribe{ println(it)}

    println(LocalDateTime.now())
}

fun printTable() {
    db.select("SELECT ID,VALUE FROM TEST_TABLE")
            .get { Item(it.getInt("ID"),it.getInt("VALUE")) }
            .subscribe { println(it) }
}
```
From what I understand with SQLite as well as MySQL, you must set the `Connection`'s `autoUpdate` to false for batching to have any benefit. The problem is when I set it to false, nothing gets committed to the database. Is there anything I am doing wrong?

**Comment by thomasnield** [comment]
Also, I noticed `returnGeneratedKeys()` will only emit the last one in each batch, not all of them. I supposed this might be a constraint of a `PreparedStatement` although I'm not sure. 

OUTPUT
```
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
```

**Comment by thomasnield** [comment]
Ah, I see what needs to be done for the commit part. `Connection#Commit` must be called when everything is done. 

```kotlin
val conn = ConnectionProviderFromUrl("jdbc:sqlite:C:/git/rxjava-jdbc-batch-test/test.db").get().apply {
    autoCommit = false
}
val db =Database.from(conn)
data class Item(val id: Int, val value: Int)

fun main(args: Array<String>) {

    println(LocalDateTime.now())

    db.update("INSERT INTO TEST_TABLE (VALUE) VALUES(?)")
        .parameters(Observable.range(1,10000))
        .batchSize(1000)
        .returnGeneratedKeys()
        .getAs(Int::class.java)
        .doOnCompleted{ conn.commit() }
        .subscribe{ println(it)}

    println(LocalDateTime.now())
}
```

Not sure if there is functionality in this library that already streamlines this. Exploring...

**Comment by thomasnield** [comment]
I see you can also use `Database#commit()` to follow the library's convention. But I'm still unsure why only the last key in each batch is emitted from `returnGeneratedKeys()`. Unless I'm doing something wrong, I think that needs to be fixed if possible.

**Comment by thomasnield** [comment]
I had a suspicion the skipping was due to the SQLite JDBC driver's implementation of returning generated keys. I installed PostgreSQL to try a different platform and found indeed this was the case. It worked fine for PostgreSQL and all generated keys were implemented. 

I approve. @davidmoten what do you think?

**Comment by EmteZogaf** [comment]
Thanks for your detailed tests @thomasnield . I'll look into testing it in sqllite once I have time in about a week.

@davidmoten I'll rebase on the latest master commit or would you like to have it rebased on another commit?

**Comment by thomasnield** [comment]
I wouldn't worry too much about SQLite. I remember reading the JDBC library has limited support for retrieving generated keys. Compared to traditional database platforms, it is a bit quirky because of its (almost spartan) lightweight architecture. 

Let me know if you guys need anything else.

**Comment by thomasnield** [comment]
@EmteZogaf, until @davidmoten gets time to review, my guess is yeah just rebase it on the master commit.

**Comment by EmteZogaf** [comment]
OK, I rebased on current master. See #49

**Comment by thomasnield** [comment]
Good, hopefully @davidmoten gets a chance to look at this soon. Thanks for putting this together @EmteZogaf, this will be invaluable for my workplace.

**Comment by davidmoten** [comment]
Closing in preference to #49

**Comment by davidmoten** [comment]
@thomasnield @EmteZogaf 
branch batch-updates contains the wip progress for this. 

One CI failure on that branch:
```
Tests in error: 
  testReturnGeneratedKeysForOneInsertedValue(com.github.davidmoten.rx.jdbc.DatabaseAsyncTest): org.h2.jdbc.JdbcSQLException: The object is already closed [90007-178]
```

**Comment by thomasnield** [comment]
Alright I'll see if I can help out the next few days. I'll put in a PR once I got something.

**Comment by thomasnield** [comment]
Hey all, I did some code review and I noticed a `  // TODO for batching we need to reuse prepared statements!` comment. 

I think this line in `QueryUpdateOnSubscribe` is preventing this from occurring. 

```java

package com.github.davidmoten.rx.jdbc;

final class QueryUpdateOnSubscribe<T> implements OnSubscribe<T> {

    ... 
    @SuppressWarnings("unchecked")
    private void performUpdate(final Subscriber<? super T> subscriber, State state) throws SQLException {
        if (subscriber.isUnsubscribed()) {
            return;
        }
        // TODO for batching we need to reuse prepared statements!
        state.ps = getPreparedStatement(state);
        Util.setParameters(state.ps, parameters, query.names());

        if (subscriber.isUnsubscribed())
            return;

        final int count;
        try {
            log.debug("executing sql={}, parameters {}", query.sql(), parameters);
            count = state.ps.executeUpdate();
            log.debug("executed ps={}", state.ps);
            if (query.returnGeneratedKeys()) {
                log.debug("getting generated keys");
                ResultSet rs = state.ps.getGeneratedKeys();
                log.debug("returned generated key result set {}", rs);
                state.rs = rs;
                Observable<Parameter> params = Observable.just(new Parameter(state));
                Observable<Object> depends = Observable.empty();
                Observable<T> o = new QuerySelect(QuerySelect.RETURN_GENERATED_KEYS, params,
                        depends, query.context(), query.context().resultSetTransform())
                                .execute(query.returnGeneratedKeysFunction());
                Subscriber<T> sub = createSubscriber(subscriber);
                o.unsafeSubscribe(sub);
            }
        } catch (SQLException e) {
            throw new SQLException("failed to execute sql=" + query.sql(), e);
        }
        if (!query.returnGeneratedKeys()) {
            // must close before onNext so that connection is released and is
            // available to a query that might process the onNext
            **close(state);  // <- this seems to be causing PreparedStatments to not be reused!**
            if (subscriber.isUnsubscribed())
                return;
            log.debug("onNext");
            subscriber.onNext((T) (Integer) count);
            complete(subscriber);
        }
    }

  ...
}
```

**Comment by davidmoten** [comment]
closing in preferency to #67

**Pull request closed without merging**
